ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Controllers/CarrinhoController.cs
using Cooperchip.ITDeveloper.Domain.Entities;
using Cooperchip.ITDeveloper.Mvc.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Cooperchip.ITDeveloper.Mvc.Controllers
{
    public class CarrinhoController : Controller
    {
        public IActionResult Index()
        {
            var produtos = new List<Produto>();
            for(int i = 1; i < 11; i++)
            {
                var n = i < 10 ? "0" + i : i +"";
                produtos.Add(new Produto
                {
                    Nome = "Prod-" + n,
                    Estoque = 3,
                    Validade = DateTime.Now,
                    Valor = 1.13M * i
                });
            }

            var model = new CarrinhoViewModel
            {
                Produtos = produtos,
                //TotalCarrinho = produtos.Sum(p=>p.Valor),
                TotalCarrinho = 13.27M,
                //Mensagem = "Obrigado por comprar conosco!"
                Mensagem = "Ah!"
            };

            //return View(model);
            return RedirectToAction("Checkout", model);
        }

        public IActionResult Checkout(CarrinhoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                if (ModelState.ErrorCount > 0)
                {
                    ViewData["semerro"] = "OPS!";
                    ModelState.AddModelError(errorMessage: "O MODELO ESTÁ INVÁLIDO", key:"erro");
                }
            }
            else
            {
                ViewData["semerro"] = "MODELO OK!";
            }

            return View(model);
        }

    }
}

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Controllers/EstadoPacienteController.cs
using Cooperchip.ITDeveloper.Data.ORM;
using Cooperchip.ITDeveloper.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Cooperchip.ITDeveloper.Mvc.Controllers
{
    public class EstadoPacienteController : Controller
    {
        private readonly ITDeveloperDbContext _context;

        public EstadoPacienteController(ITDeveloperDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.EstadoPaciente.ToListAsync());
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadoPaciente = await _context.EstadoPaciente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estadoPaciente == null)
            {
                return NotFound();
            }

            return View(estadoPaciente);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Descricao,Id")] EstadoPaciente estadoPaciente)
        {
            if (ModelState.IsValid)
            {
                estadoPaciente.Id = Guid.NewGuid();
                _context.Add(estadoPaciente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estadoPaciente);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadoPaciente = await _context.EstadoPaciente.FindAsync(id);
            if (estadoPaciente == null)
            {
                return NotFound();
            }
            return View(estadoPaciente);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Descricao,Id")] EstadoPaciente estadoPaciente)
        {
            if (id != estadoPaciente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estadoPaciente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstadoPacienteExists(estadoPaciente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estadoPaciente);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estadoPaciente = await _context.EstadoPaciente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estadoPaciente == null)
            {
                return NotFound();
            }

            return View(estadoPaciente);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var estadoPaciente = await _context.EstadoPaciente.FindAsync(id);
            _context.EstadoPaciente.Remove(estadoPaciente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstadoPacienteExists(Guid id)
        {
            return _context.EstadoPaciente.Any(e => e.Id == id);
        }
    }
}

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Controllers/PacienteController.cs
using Cooperchip.ITDeveloper.Data.ORM;
using Cooperchip.ITDeveloper.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace Cooperchip.ITDeveloper.Mvc.Controllers
{
    [Authorize]
    public class PacienteController : Controller
    {
        private readonly ITDeveloperDbContext _context;

        public PacienteController(ITDeveloperDbContext context)
        {
            _context = context;
        }

        // GET: Paciente
        public async Task<IActionResult> Index()
        {
            return View(await _context.Paciente
                .Include(x => x.EstadoPaciente).AsNoTracking().ToListAsync());
        }

        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.Include(x=>x.EstadoPaciente).AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        public IActionResult Create()
        {
            ViewBag.EstadoPaciente = new SelectList(_context.EstadoPaciente, "Id", "Descricao");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                //paciente.Id = Guid.NewGuid(); // Não Usar
                _context.Add(paciente);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Index");
            }
            ViewBag.EstadoPaciente = new SelectList(_context.EstadoPaciente, "Id", "Descricao", paciente.EstadoPacienteId);
            return View(paciente);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.FindAsync(id);
            if (paciente == null)
            {
                return NotFound();
            }
            ViewBag.EstadoPaciente = new SelectList(_context.EstadoPaciente, "Id", "Descricao", paciente.EstadoPacienteId);
            return View(paciente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Paciente paciente)
        {
            if (id != paciente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paciente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PacienteExists(paciente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.EstadoPaciente = new SelectList(_context.EstadoPaciente, "Id", "Descricao", paciente.EstadoPacienteId);
            return View(paciente);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.Include(x=>x.EstadoPaciente).AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var paciente = await _context.Paciente.FindAsync(id);
            _context.Paciente.Remove(paciente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PacienteExists(Guid id)
        {
            return _context.Paciente.Any(e => e.Id == id);
        }
    }
}

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cooperchip.ITDeveloper.Mvc.Controllers
{
    public class ProdutoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Lista()
        {
            return View();
        }

    }
}

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Views/Shared/PartialViews/_estado_paciente.cshtml
<div class="panel panel-info">

    <div class="panel panel-heading"><h4>Estado dos Pacientes</h4></div>

    <div class="panal panel-body">

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <vc:estado-critico></vc:estado-critico>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <vc:estado-estavel></vc:estado-estavel>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <vc:estado-grave></vc:estado-grave>
        </div>

        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <vc:estado-observacao-view-components></vc:estado-observacao-view-components>
        </div>

    </div>

</div>

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Views/Shared/PartialViews/_footer.cshtml
<div id="footer" class="clearfix sidebar-page right-sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
        Copyrights &copy; 2014 / @DateTime.Now.Year.ToString() <a href="http://eaditdeveloper.com.br/" class="color-blue strong" target="_blank">EAD IT Developer</a>. Todos os direitos reservados.
    </p>
    <p>
        &nbsp; <email dominio="gmail.com">contato</email>   -   <email>contato</email>   
    </p>

    <p class="pull-right">
        <a href="#" class="mr5">Terms of use</a>
        |
        <a href="#" class="ml5 mr25">Privacy police</a>
    </p>
</div>
<!-- End #footer  -->

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Views/Shared/PartialViews/_head.cshtml
    <head>
        <meta charset="utf-8">
        <title>@ViewData["Title"] - EAD - ITDeveloper</title>
        <!-- Mobile specific metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1 user-scalable=no">
        <!-- Force IE9 to render in normal mode -->
        <!--[if IE]><meta http-equiv="x-ua-compatible" content="IE=9" /><![endif]-->
        <meta name="author" content="" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta name="application-name" content="" />
        <!-- Import google fonts - Heading first/ text second -->
        @*<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700' rel='stylesheet' type='text/css'>*@

        @* ======================================================== *@

        <!-- Css files -->
        <!-- Icons -->
        <link href="~/bundle/core.min.css" rel="stylesheet" />

        @* ======================================================== *@


        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="img/ico/apple-touch-icon-57-precomposed.png">
        <link rel="icon" href="img/ico/favicon.ico" type="image/png">
        <!-- Windows8 touch icon ( http://www.buildmypinnedsite.com/ )-->
        <meta name="msapplication-TileColor" content="#3399cc" />
    </head>

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Views/Shared/PartialViews/_layout_original.cshtml
@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Cooperchip.ITDeveloper.Mvc</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  crossorigin="anonymous"
                  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
        </environment>
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cooperchip.ITDeveloper.Mvc</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - Cooperchip.ITDeveloper.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)
    </body>
    </html>*@

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Views/Shared/PartialViews/_lis_do_menu_left.cshtml
<li>
    <a asp-controller="Home" asp-action="Index"><i class="l-basic-laptop"></i><span class="txt">Dashboard</span></a>
</li>

<li>
    <a href="#"><i class="l-ecommerce-graph1"></i> <span class="txt">Demo - Rotas</span></a>
    <ul class="sub">
        <li>
            <a asp-controller="Home" asp-action="Index"><span class="txt">Home</span></a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="Icones"><span class="txt">Icones</span></a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="Privacy"><span class="txt">Privacidade </span></a>
        </li>
        <li>
            <a asp-controller="Home" asp-action="Error"><span class="txt">Erro </span></a>
        </li>
    </ul>
</li>

<li>
    <a asp-controller="Carrinho" asp-action="Index"><i class="l-basic-anchor"></i><span class="txt">Carrinho</span></a>
</li>

<li>
    <a asp-controller="Paciente" asp-action="Index"><i class="l-basic-chronometer"></i><span class="txt">Pacientes</span></a>
</li>

<li>
    <a asp-controller="EstadoPaciente" asp-action="Index"><i class="l-basic-accelerator"></i><span class="txt">Estado Pacientes</span></a>
</li>



<li>
    <a href="#"><i class="l-ecommerce-graph1"></i> <span class="txt">Produtos</span></a>
    <ul class="sub">
        <li>
            <a asp-controller="Produto" asp-action="Index"><span class="txt">Produtos</span></a>
        </li>
        <li>
            <a asp-controller="Produto" asp-action="Lista"><span class="txt">Lista de Produtos</span></a>
        </li>
    </ul>
</li>



























@* Links originais da template *@


@*<li>
        <a href="#"><i class="l-ecommerce-graph1"></i> <span class="txt">Charts</span></a>
        <ul class="sub">
            <li>
                <a href="charts-flot.html"><span class="txt">Flot charts</span></a>
            </li>
            <li>
                <a href="charts-morris.html"><span class="txt">Morris charts</span></a>
            </li>
            <li>
                <a href="charts-chartjs.html"><span class="txt">Chartjs </span></a>
            </li>
            <li>
                <a href="charts-other.html"><span class="txt">Other charts</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-basic-webpage-txt"></i><span class="txt">Forms</span></a>
        <ul class="sub">
            <li>
                <a href="forms-basic.html"><span class="txt">Basic forms</span></a>
            </li>
            <li>
                <a href="forms-advanced.html"><span class="txt">Advanced forms</span></a>
            </li>
            <li>
                <a href="forms-layouts.html"><span class="txt">Form layouts</span></a>
            </li>
            <li>
                <a href="forms-wizard.html"><span class="txt">Form wizard</span></a>
            </li>
            <li>
                <a href="forms-validation.html"><span class="txt">Form validation</span></a>
            </li>
            <li>
                <a href="code-editor.html"><span class="txt">Code editor</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-software-layout-header-3columns"></i><span class="txt">Tables</span></a>
        <ul class="sub">
            <li>
                <a href="tables-basic.html"><span class="txt">Basic tables</span></a>
            </li>
            <li>
                <a href="tables-data.html"><span class="txt">Data tables</span></a>
            </li>
            <li>
                <a href="tables-editable.html"><span class="txt">Editable tables</span></a>
            </li>
            <li>
                <a href="tables-ajax.html"><span class="txt">Ajax tables</span></a>
            </li>
            <li>
                <a href="tables-pricing.html"><span class="txt">Pricing tables</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-software-layers2"></i><span class="txt">UI Elements</span></a>
        <ul class="sub">
            <li>
                <a asp-controller="Home" asp-action="Icones"><span class="txt">Ícones</span></a>
            </li>
            <li>
                <a href="typography.html"><span class="txt">Typography</span></a>
            </li>
            <li>
                <a href="tabs.html"><span class="txt">Tabs</span></a>
            </li>
            <li>
                <a href="accordions.html"><span class="txt">Accordions</span></a>
            </li>
            <li>
                <a href="buttons.html"><span class="txt">Buttons</span></a>
            </li>
            <li>
                <a href="notifications.html"><span class="txt">Notifications</span></a>
            </li>
            <li>
                <a href="modals.html"><span class="txt">Modals</span></a>
            </li>
            <li>
                <a href="sliders.html"><span class="txt">Sliders</span></a>
            </li>
            <li>
                <a href="progressbars.html"><span class="txt">Progressbars</span></a>
            </li>
            <li>
                <a href="lists.html"><span class="txt">Lists</span></a>
            </li>
            <li>
                <a href="grid.html"><span class="txt">Grid</span></a>
            </li>
            <li>
                <a href="ui-other.html"><span class="txt">Other</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="portlets.html"><i class="l-software-layout-header"></i><span class="txt">Portlets</span><span class="label">22</span></a>
    </li>
    <li>
        <a href="#"><i class="l-basic-mail"></i> <span class="txt">Email</span></a>
        <ul class="sub">
            <li>
                <a href="email-inbox.html"><span class="txt">Inbox</span></a>
            </li>
            <li>
                <a href="email-read.html"><span class="txt">Read email</span></a>
            </li>
            <li>
                <a href="email-write.html"><span class="txt">Write email</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-basic-geolocalize-01"></i><span class="txt">Maps</span></a>
        <ul class="sub">
            <li>
                <a href="maps-google.html"><span class="txt">Google maps</span></a>
            </li>
            <li>
                <a href="maps-vector.html"><span class="txt">Vector maps</span></a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#"><i class="l-basic-webpage"></i><span class="txt">Pages</span></a>
        <ul class="sub">
            <li>
                <a href="login.html"><span class="txt">Login</span></a>
            </li>
            <li>
                <a href="lock-screen.html"><span class="txt">Lock screen</span></a>
            </li>
            <li>
                <a href="register.html"><span class="txt">Register</span></a>
            </li>
            <li>
                <a href="lost-password.html"><span class="txt">Lost password</span></a>
            </li>
            <li>
                <a href="profile.html"><span class="txt">User profile</span></a>
            </li>
            <li>
                <a href="calendar.html"><span class="txt">Calendário</span></a>
            </li>
            <li>
                <a href="timeline.html"><span class="txt">Timeline</span></a>
            </li>
            <li>
                <a href="gallery.html"><span class="txt">Gallery</span></a>
            </li>
            <li>
                <a href="invoice.html"><span class="txt">Invoice</span></a>
            </li>
            <li>
                <a href="blank.html"><span class="txt">Blank page</span></a>
            </li>
            <li>
                <a href="#"><span class="txt">Error pages</span></a>
                <ul class="sub">
                    <li>
                        <a href="403.html"><span class="txt">403</span></a>
                    </li>
                    <li>
                        <a href="404.html"><span class="txt">404</span></a>
                    </li>
                    <li>
                        <a href="500.html"><span class="txt">500</span></a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>*@

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Views/Shared/PartialViews/_menu_inferior_left.cshtml
<!--  .sidebar-panel -->
<div class="sidebar-panel">
    <h5 class="sidebar-panel-title">Server stats</h5>
    <div class="sidebar-panel-content">
        <div class="sidebar-stat mb10">
            <p class="color-white mb5 mt5">
                <i class="fa fa-hdd-o mr5"></i> Disk Space <span class="pull-right small">30%</span>
            </p>
            <div class="progress flat transparent progress-bar-xs">
                <div class="progress-bar progress-bar-white" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%;"></div>
            </div>
            <span class="dib s12 mt5 per100 text-center">3001.56 / 10000 MB</span>
        </div>
        <div class="sidebar-stat">
            <p class="color-white mb5 mt5">
                <i class="glyphicon glyphicon-transfer mr5"></i> Bandwidth Transfer <span class="pull-right small">78%</span>
            </p>
            <div class="progress flat transparent progress-bar-xs">
                <div class="progress-bar progress-bar-white" role="progressbar" aria-valuenow="78" aria-valuemin="0" aria-valuemax="100" style="width: 78%;"></div>
            </div>
            <span class="dib s12 mb10 mt5 per100 text-center">87565.12 / 120000 MB</span>
        </div>
    </div>
</div>

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Views/Shared/PartialViews/_profile_left_sidebar.cshtml
<!--  .sidebar-panel -->
<div class="sidebar-panel">
    <h5 class="sidebar-panel-title">Profile</h5>
</div>
<!-- / .sidebar-panel -->


<div class="user-info clearfix">
    <img src="img/avatars/128.jpg" alt="avatar">
    <span class="name">SuggeElson</span>
    <div class="btn-group">
        <button type="button" class="btn btn-default btn-xs">
            <i class="l-basic-gear"></i>
        </button>
        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
            settings <span class="caret"></span>
        </button>
        <ul class="dropdown-menu right" role="menu">
            <li>
                <a href="profile.html"><i class="fa fa-edit"></i>Edit profile</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-money"></i>Windraws</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-credit-card"></i>Deposits</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="login.html"><i class="fa fa-power-off"></i>Logout</a>
            </li>
        </ul>
    </div>
</div>
<!--  .sidebar-panel -->

ITDevelope/src/Cooperchip.ITDeveloper.Mvc/Views/Shared/PartialViews/_scripts.cshtml
<!-- Javascripts -->
<!-- Load pace first -->
<script src="~/plugins/core/pace/pace.min.js"></script>
<!-- Important javascript libs(put in all pages) -->

<script src="~/jQuery/jquery.js"></script>

<script src="~/jQuery/jquery-ui.js"></script>



<!--[if lt IE 9]>
  <script type="text/javascript" src="js/libs/excanvas.min.js"></script>
  <script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <script type="text/javascript" src="js/libs/respond.min.js"></script>
<![endif]-->
<!-- Bootstrap plugins -->

<script src="~/bundle/core.min.js"></script>

<!-- Other plugins ( load only nessesary plugins for every page) -->

<script src="~/js/libs/date.js"></script>
<script src="~/bundle/jQueryFlot.min.js"></script>
<script src="~/bundle/core.dashboard.min.js"></script>

@* ==================================================================== *@

<script src="~/plugins/misc/vectormaps/jquery-jvectormap-1.2.2.min.js"></script>
<script src="~/plugins/misc/vectormaps/maps/jquery-jvectormap-world-mill-en.js"></script>
<script src="~/plugins/misc/countTo/jquery.countTo.js"></script>
<script src="~/js/jquery.dynamic.js"></script>
<script src="~/js/main.js"></script>
<script src="~/js/pages/dashboard.js"></script>